### ISSUE TITLE
Idiomatic install

### ISSUE THREAD

**Issue by ytti** [OpenIxia/IxNetwork#10]
What is the recommended way to install this in your own python projects?

Idiomatically I'd like to use pip:
```
cat >> requirements.txt
-e git+https://github.com/OpenIxia/IxNetwork#egg=ixnetwork
^D
```

But this won't work because you do not have 'setup.py'. And the organisation of the repository does not really support this. You'd need separate repositories for lowlevel, highlevel, rest etc.

If you want example how to make your repository pip installable, look for example textfsm:
```-e git+https://github.com/google/textfsm.git#egg=textfsm```

**Comment by iwanb** [comment]
If they add the setup.py you can use the subdirectory parameter of pip to select a subdirectory of the repository as the root of the package:
`-e git+https://github.com/OpenIxia/IxNetwork#egg=ixnetwork&subdirectory=RestPy`

I guess for now you need to use the packages uploaded by Ixia.

**Comment by hubertgee** [comment]
No plans to do this for this utility.  Recommending to use RestPy.
