### ISSUE TITLE
AresOne: "Random" Frame Payload Type setting 0s in payload on IxNetwork

### ISSUE THREAD

**Issue by rbandana** [OpenIxia/IxNetwork#100]
On using Frame Payload Function 
**ixnetwork_restpy.testplatform.sessions.ixnetwork.traffic.trafficitem.configelement.framepayload.framepayload.FramePayload** 
on IxNetworkWeb, the packet is updated with a empty payload  when 
 Frame Payload Type=**"Random"** 

![image](https://user-images.githubusercontent.com/59622570/81882166-df033480-9546-11ea-921e-69db61b72010.png)

**Comment by priteshjmodi** [comment]
Hello, can you provide us more details where this issue is transferred and if there is any workaround / solution meanwhile?

**Comment by ajbalogh** [comment]
The issue has been transferred to https://github.com/OpenIxia/IxNetwork/issues
The ixnetwork-restpy package is a thin wrapper around the IxNetwork REST API.This is not a specific ixnetwork-restpy issue but an IxNetwork traffic issue.
A support team member will open a bug for this issue and reply back on this issue.

**Comment by therkong** [comment]
Hi Pritesh,   I opened support Case #898274 for you.   I will look into this and get back to you.
Are you with Intel (formerly Barefoot Networks)?

**Comment by priteshjmodi** [comment]
Thank you. Yes, we are with Intel (Barefoot networks). Please add @rbandana in this case.

**Comment by therkong** [comment]
Provided hotfix on top of 9.05
HF000922: AresOne - traffic item with frame payload type = 'random' does not work. Capture on Rx port shows payload with all 0s.
