### ISSUE TITLE
Ixnetwork.AssignPorts() hangs when a license error occurs

### ISSUE THREAD

**Issue by alexandreseitz** [OpenIxia/IxNetwork#101]
When license error occurs, the method TestPlatform.Sessions.Ixnetwork.AssignPorts() hangs without raising any Exception. I need to be able to catch an exception when such error occurs.
It could be nice to configure a timeout to wait for before raise an Exception.

my development environment os:
python3.7
ixnetwork_restpy==1.0.43
Ixnetwork 9.00

**Comment by therkong** [comment]
Hi,  sorry for the delayed response.  
Have you used PortMapAssistant and SessionAssistant?  These makes coding in RestPy much simpler.
Here's example code snip to assignPorts using PortMapAssistant:
    session = SessionAssistant(IpAddress='10.36.88.91', UserName='tkong', Password='tkong', 
                               ClearConfig=True, LogLevel='request_response', LogFilename='restpy.log')
    ixNetwork = session.Ixnetwork
    portMap = session.PortMapAssistant()
    vport1 = portMap.Map(IpAddress='10.36.88.91', CardId=6, PortId=1, Name='Port_1')
    vport2 = portMap.Map(IpAddress='10.36.88.91', CardId=6, PortId=2, Name='Port_2')
    portMap.Connect(ForceOwnership=True)

If there's license error, the portMap.Connect() will fail and raise NoteFoundError Exception.
You'll see an error message on the console:
"ixnetwork_restpy.errors.NotFoundError: After 300 seconds the Port Statistics view does not exist."

Note: you can update the timeout value by passing in LinkUpTimeout parameter.  For example:
portMap.Connect(ForceOwnership=True, LinkUpTimeout=100)

In the exception clause, you can print out appErrors.Error.Description.  One of the error should be license error.
Code snip:
except Exception as errMsg:
    print('\n%s' % traceback.format_exc(None, errMsg))
    apperrors = ixNetwork.Globals.AppErrors.find()
    errorCount = apperrors.ErrorCount
    ixNetwork.info(apperrors)
    for range in (0, errorCount):
        error = apperrors.Error.find()[range]
        ixNetwork.info(error.Description)
        if debugMode == False and 'session' in locals():
            session.Session.remove()

Sample output:
2020-07-28 21:25:05 [ixnetwork_restpy.connection] [INFO] AppErrors[0]: /api/v1/sessions/27/ixnetwork/globals/appErrors
        ErrorCount: 2
        LastModified: 07/28/2020 07:14:57
        WarningCount: 0

Let me know if you have any questions on this.

**Comment by therkong** [comment]
here's the sample output with license error:
Sample output:
2020-07-28 21:25:05 [ixnetwork_restpy.connection] [INFO] AppErrors[0]: /api/v1/sessions/27/ixnetwork/globals/appErrors
        ErrorCount: 2
        LastModified: 07/28/2020 07:14:57
        WarningCount: 0

2020-07-28 21:25:13 [ixnetwork_restpy.connection] [INFO] ixNet API Service listening on 0.0.0.0:35155

2020-07-28 21:25:18 [ixnetwork_restpy.connection] [INFO] Not enough subscription licenses available for HW ports.
Requested = 1, Granted = 0, Installed = 0
Features = IXN-TIER3; IXN-TIER2; IXN-TIER1
Servers = 192.0.0.1

**Comment by alexandreseitz** [comment]
Hi, 

today, I don't use PortMapAssistant but AssignPorts. I will study your proposal . thanks

**Comment by therkong** [comment]
Hi Alex,
Were you able to try PortMapAssistant?   Let me know if this issue is resolved or not.

**Comment by alexandreseitz** [comment]
Hello Finally,
I prefer to don't use the PortMapAssistant, 
I have fixed my issue by using Ixnetwork.AssignPorts()
regards
