### ISSUE TITLE
IxNetwork hanging with error log in IxMonitor

### ISSUE THREAD

**Issue by wengm** [OpenIxia/IxNetwork#102]
Hi,

These days, we faced the problem frequently: after below command, it stuck there forever until timeout and the process is forcely terminated.
`Command: ixNet connect [Ixia app server IP] -version [Ixia tcl lib version]`
And I observed the error log in IxMonitor log file at the same moment:

> 2020.05.15 01:13:39 25924 IxNetwork.RBProtocols#12(1UAC-X0840475\cmgruser4):Watch evaluation error: Instance 'IxNetwork.RBProtocols#12' does not exist in the specified Category.

We used Connection Mananger to manage IxNetwork pools.
Not sure if you can help on this.

Br,
Bruce Wen

**Comment by therkong** [comment]
Hi Bruce,

For this type of issue, it’s best to  open a support ticket.  You can open a ticket by sending email to support.ix@keysight.com<mailto:support.ix@keysight.com>.  Please include the license info or activation code of ixNetwork.
Once a support ticket is opened, one of Keysight support engineer will work with you to debug this issue.


Regards,
Theresa

**Comment by wengm** [comment]
Yes, asked ixia support to help.
