### ISSUE TITLE
is there an equivalent api for capture like takecsvsnapshot in RestPy

### ISSUE THREAD

**Issue by muthvar1** [OpenIxia/IxNetwork#104]
I am basically looking for an api in RestPy that takes the capture of a given vport and then also saves the file to the local _root_directory. I have the below commands. But this saves it locally on the ixNetworkClient. I need the file transferred to my local _root_directory.

ixnetwork.Vport.find(Name='1/1/13').Capture.HardwareEnabled = True

ixnetwork.StartCapture()
ixnetwork.Traffic.Apply()
ixnetwork.Traffic.Start()
flowStatistics = StatViewAssistant(ixnetwork, 'Flow Statistics')
ixnetwork.StopCapture()
ixnetwork.SaveCaptureFiles("C:\Results", "trace.pcap")

**Comment by therkong** [comment]
Hi,

In TestPlatform.Sessions(), there's DownloadFile() to download the file to your local machine.   check: https://openixia.github.io/ixnetwork_restpy/#/reference

""" Method Sessions.DownloadFile

Download a file from the IxNetwork session instance

Args
----
- remote_fileanme (str): the name of the remote file
- local_filename (str): the name that the remote contents will be saved to

Returns
-------
- str: the local file name
"""
# This auto generated sample is based on the following assumptions:
# - there is at least one session active
# - the session configuration contains at least one resource for every class present in the sample
from ixnetwork_restpy import TestPlatform


sessions = TestPlatform('127.0.0.1') \
	.Sessions.find()
sessions.DownloadFile(remote_filename, local_filename=None)

**Comment by muthvar1** [comment]
HI Theresa,
Is this DownloadFile a new addition to the SDK? I don't see it in my earlier versions

**Comment by therkong** [comment]
It’s been there for a while.   Please check RestPy API guide:  https://openixia.github.io/ixnetwork_restpy/#/reference
DownloadFile is under TestPlatform->Sessions

What is your ixnetwork_restpy version?


Regards,
Theresa

**Comment by ajbalogh** [comment]
https://github.com/OpenIxia/ixnetwork_restpy/blob/master/RELEASENOTES.md#feb2019

**Comment by muthvar1** [comment]
It's weird. I can see it in my version of the codebase in the sessions module. But for some reason, I cannot access the method. I need to debug more.

**Comment by muthvar1** [comment]
Sorry, I had accindentally pointed my code base to an older SDK. Corrected it now. But I still see some issue with the file download. Is the expectation for all files to be stored in a manged filePath?

ixnetwork.Vport.find(Name='1/1/13').Capture.HardwareEnabled = True

ixnetwork.StartCapture()
ixnetwork.Traffic.Apply()
ixnetwork.Traffic.Start()
flowStatistics = StatViewAssistant(ixnetwork, 'Flow Statistics')
ixnetwork.StopCapture()
remote_filename = ixnetwork.SaveCaptureFiles("C:\Results", "capture")[0]
print remote_filename
C:\Results\1-1-13_HWcatapult.cap
session.DownloadFile(remote_filename,local_filename='/local/vamuthal')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    session.DownloadFile(remote_filename,local_filename='/local/vamuthal')
  File "/local/vamuthal/IxiaSDK/ixnetwork_restpy/testplatform/sessions/sessions.py", line 211, in DownloadFile
    return self._connection._get_file('%s/ixnetwork' % self.href, remote_filename=remote_filename, local_filename=local_filename)
  File "/local/vamuthal/IxiaSDK/ixnetwork_restpy/connection.py", line 189, in _get_file
    self._process_response_status_code(response)
  File "/local/vamuthal/IxiaSDK/ixnetwork_restpy/connection.py", line 215, in _process_response_status_code
    raise ServerError(response)
ServerError: http://10.195.217.111:11009/api/v1/sessions/1/ixnetwork/files?filename=C:%5CResults%5C1-1-13_HWcatapult.cap&deprecated=true => 403 Forbidden {"me
thod":"GET","pathAndQuery":"/api/v1/sessions/1/ixnetwork/files?filename=C:%5CResults%5C1-1-13_HWcatapult.cap&deprecated=true","errors":[{"code":403,"detail":"
Forbidden: The file path C:\\Results\\1-1-13_HWcatapult.cap is not under one of the following system managed file paths: C:/Users/ixia/AppData/Local/Ixia (rea
d/write)"}]}
>>>
>>>

**Comment by muthvar1** [comment]
Looks like it only allows downloads from specific file systems. I see that it is a server-side error, not sure if it is a restriction on the ixNetwork API server or the Windows system as such. Can someone help explain? I would ideally like to not store the captured files under C:\Users\ixia\AppData\Local\Ixia. This is because we have autopurge routines that run on the client VMs that do not take this folder into consideration.

**Comment by therkong** [comment]
I will test this out and let you know.

Regards,
Theresa

**Comment by therkong** [comment]
I’d like to open a support ticket to keep track of this… Can you send me your company email account?

Regards,
Theresa

**Comment by therkong** [comment]
I tried out in my setup.  Indeed, the capture file must be save under C:\Users\ixia\AppData\Local\Ixia.   I checked with our engineer.    It's for security reasons that we limit where you can write the files.  Did you want to remove the capture files with your autopurge routine?   Is it possible to add more paths to your autopurge?

**Comment by muthvar1** [comment]
Hi Theresa,
I will see if we can add this folder to our auto-purge in that case.

Thanks,
Varghese
