### ISSUE TITLE
Links to code on openixia.com website failing

### ISSUE THREAD

**Issue by NickKeating** [OpenIxia/IxNetwork#107]
Hi, 

Was not sure where the best place to bring this to attention was, or if you are already aware. But clicking the link highlighted in the red in the below screenshot at URL https://openixia.amzn.keysight.com/apis/showRestApi/IxNetRestApiClassicProtocol.py is getting a traceback error at the moment. 

![image](https://user-images.githubusercontent.com/26047827/86190415-a6b3c600-bb87-11ea-8b64-7cfc121cf1db.png)

Traceback as below:

![image](https://user-images.githubusercontent.com/26047827/86190431-ad423d80-bb87-11ea-92bc-09b427a5b049.png)

Regards, 
Nick

**Comment by hubertgee** [comment]
Thanks Nick.  It is fixed now.
