### ISSUE TITLE
IxNetRestApiProtocol.py missing method to create loopback

### ISSUE THREAD

**Issue by ytti** [OpenIxia/IxNetwork#11]
IxNetRestApiProtocol.py can create ipv4 protocol object, but cannot create ipv4 loopback protocol object

Is there swagger browser somewhere, to easily show how to build correct query/JSON?

**Comment by hubertgee** [comment]
Hi Ytti,

configLoopbackPort is added to IxNetRestApyPortMgmt.py.

Yes.  Starting with IxNetwork 8.40, there is an API browser tool that shows you all the REST APIs.  On your Windows GUI, create a configuration.  Then go to File, Tools, IxNetwork API Browser.  The left pane shows the API tree beginning at the root level for each component entry point.  Click around to navigate and click on the green history button.  It will show you all the REST APIs, Python syntaxes and results that you clicked whether it was a GET , PATCH or POST. 

A video tutorial:  http://openixia.com/tutorialMainPage under Tutorial Videos.
