### ISSUE TITLE
::ixNet::ERROR-7008-Could not apply traffic,Error in L2/L3 Traffic Apply

### ISSUE THREAD

**Issue by wengm** [OpenIxia/IxNetwork#110]
Hi,

After the command "ixNet exec apply [ixNet getRoot]traffic", it got:
::ixNet::ERROR-7008-Could not apply traffic,Error in L2/L3 Traffic Apply

Any way to show more details of the error?

Thanks

**Comment by therkong** [comment]
Are you using Windows ixNet API Server?   If yes, you can open Error/Warning window via the 'Messages' on the bottom right.  You need to click the word 'Messages'.
If you are running Linux API Server, then you can open the API Browser and go to globals/appErrors.     Hope this helps.

**Comment by wengm** [comment]
@therkong  Thanks. 
And what I meant is to show more details by command, if any. Then I can got it in the reply and have better understanding on the error.

**Comment by therkong** [comment]
Here's code snip:
        Errors = []
        Messages = ixNet.getList('::ixNet::OBJ-/globals/appErrors', 'error')
        for Message in Messages:
            if ixNet.getAttribute(Message, '-errorLevel') == 'kError':
                Errors.append("\n{" + ixNet.getAttribute(Message, '-provider') + "}\n"
                              + ixNet.getAttribute(Message, '-name') + "Description: "
                              + ixNet.getAttribute(Message, '-description') + "\n")
        if Errors != []:
            raise UtilsError(Errors)

T          or you can print the Errors
