### ISSUE TITLE
new SDK does not support 8.51

### ISSUE THREAD

**Issue by muthvar1** [OpenIxia/IxNetwork#112]
Hi, I see that the new SDK does not support clients older than 8.52? This was not the case in the older SDK.

ixnetwork_restpy/testplatform/sessions/sessions.py
Old SDK
from distutils.version import LooseVersion
        if LooseVersion(build_number) < LooseVersion('8.42'):
            raise ValueError('IxNetwork server version %s is not supported. The minimum version supported is 8.42' % build_number)
        ixnetwork._set_properties(ixnetwork._connection._read('%s/%s' % (self.href, Ixnetwork._SDM_NAME)))

NEW SDK
 File "/local/vamuthal/IxiaSDKNew/ixnetwork_restpy/testplatform/sessions/sessions.py", line 55, in Ixnetwork
    raise ValueError('IxNetwork server version %s is not supported. The minimum version supported is 8.52' % build_number)
ValueError: IxNetwork server version 8.51.1810.5 is not supported. The minimum version supported is 8.52

**Comment by therkong** [comment]
Hi, 

In RestPy Ref Guide, we state the minimum supported version is 8.52:
https://openixia.github.io/ixnetwork_restpy/#/overview

![image](https://user-images.githubusercontent.com/35854929/89059612-5bbbd880-d316-11ea-8bce-29f7cb019f09.png)

It is also stated in:
https://github.com/OpenIxia/ixnetwork_restpy#supported-server-versions

In pre 8.52 versions, Rest controller didn’t support keep alives and as a result the python requests library will continually establish a new socket for every request, hence it is not as efficient and users may hit intermittent connection related issues.
