### ISSUE TITLE
Why isDataCaptureRunning is false?

### ISSUE THREAD

**Issue by wengm** [OpenIxia/IxNetwork#113]
Hi,

After starting capture,
```
% ixNet exec start ::ixNet::OBJ-/vport:1/capture allTraffic;after 30000
```

I got:
```
% ixNet getA ::ixNet::OBJ-/vport:1/capture -isDataCaptureRunning
% false
% ixNet getA ::ixNet::OBJ-/vport:1/capture -isControlCaptureRunning
% true
```

What might cause -isDataCaptureRunning is false?

**Comment by therkong** [comment]
Did you enable Data capture?   It is enabled by setting -softwareEnabled to true.   See code snip:
ixNet setAttribute $vPort/capture -softwareEnabled true
ixNet commit

**Comment by wengm** [comment]
Yes, enabled both.

```
% ixNet getAttr $vPort/capture -softwareEnabled
% true
% ixNet getAttr $vPort/capture -hardwareEnabled
% true
```

**Comment by therkong** [comment]
Can you try it from GUI?  Maybe the card type you're using does not support data capture (just guessing).    You can also
open a support ticket by sending email to support.ix@keysight.com.   One of our automation support team member can help you debug.

**Comment by wengm** [comment]
Maybe it depends on traffic stream configuration. For some test case, only -isControlCaptureRunning is true, for other test cases both are true. 

I will check further.

**Comment by therkong** [comment]
traffic stream should not affect the capture buffer.   Do you have the ixNet Linux API Server?  If you have Windows API Server, it's easy to see if the Data Capture is enabled or not.  For Linux API Server, open the API Browser and check if the Data Capture buffer is enabled or not.  
![image](https://user-images.githubusercontent.com/35854929/89056771-64f67680-d311-11ea-9055-13664283c29a.png)
