### ISSUE TITLE
How to read vport object

### ISSUE THREAD

**Issue by narasimha928** [OpenIxia/IxNetwork#116]
Hi Team,

I am using Ixia RestPy for automation. during the automation i observed vport is a dict and it is returing key:val and val is a object. How would i know what values does it contain. Please let me know.

In [31]: vport                                                                              
Out[31]: 
{'Port_1': <ixnetwork_restpy.testplatform.sessions.ixnetwork.vport.vport.Vport at 0x7ffb71b172d0>,
 'Port_2': <ixnetwork_restpy.testplatform.sessions.ixnetwork.vport.vport.Vport at 0x7ffb71932b88>}

isinstance(vport['Port_1'],object) 

Here Poet_1 is a key and val is a object.

Thanks
Narasimha

**Comment by therkong** [comment]
The value in vport['Port_1'] is <ixnetwork_restpy.testplatform.sessions.ixnetwork.vport.vport.Vport at 0x7ffb71b172d0> which is RestPy Ixnetwork.Vport object.   You can print out the attribute of this object with print().    You can try print(vport['Port_1']).  It should show all the attributes and their values:
![image](https://user-images.githubusercontent.com/35854929/92667402-b276e380-f2c0-11ea-82dd-deca8d8557da.png)

**Comment by therkong** [comment]
Please check  https://openixia.github.io/ixnetwork_restpy/#/  for sample scripts and API reference guide.

**Comment by narasimha928** [comment]
Thanks a lot for the feedback.i will check it.
