### ISSUE TITLE
Any timeout for one session

### ISSUE THREAD

**Issue by wengm** [OpenIxia/IxNetwork#117]
Hi,

I got "IOException when reading sock1" when I keep using one session in automation test. Is it caused by socket connection timeout?

Anybody has solution for it?

Br,
Bruce Wen

**Comment by therkong** [comment]
Hi Bruce,
Was the socket idle for 30 min or longer?   I don't think ixNet API Server have timeout for socket connection internally; however if a socket is idle for a long time, maybe there's tcp timeout setting done on Linux box or firewall, ...etc.

**Comment by wengm** [comment]
@therkong 

I tried to send command "ixNet getA [ixNet getRoot]traffic -state" to keep the socket connection be active and survive after 30 minutes. However, it doesn't work. The IOException still happen when it disconnect from IxNetwork.

I used connection manager.

My understanding is Tcl client connection or disconnect to IxNetwork is for socket to port 8009, but ixNet command should use different port which assigned by connection manager. For example, below example, it should use 8022 for Tcl command sending and response receiving. Is that right? 
```
2020-09-29 05:54:05  INFO  TclSession:494 - Command: ixNet connectiontoken
2020-09-29 05:54:05  INFO  TclSession:494 - Output: -processid 63780 -sessionid 8022 -port 8022  -tclport 8022 -serverusername cmgruser2 -state active -starttime 20200929_05:54:12 -host 10.67.31.48 -closeServerOnDisconnect True -clientusername egugwen -restport 11022
```

**Comment by therkong** [comment]
Do you still have this issue?  If yes, can you open a support ticket?  You can open a support ticket by sending email to support.ix@keysight.com with your ixNetwork activation code.    Once it's opened, either I or one of our automation support team member can work with you.
