### ISSUE TITLE
What's sdmPort used for?

### ISSUE THREAD

**Issue by wengm** [OpenIxia/IxNetwork#119]
Hi,

It shows sdmPort 9020 when I run command "ixNet setSessionParameter"

`publisherVersion 8.50 logfile none decorateExecReturn True enablePublishError True enablePublishWarning False enablePublishInfo False sdmPort 9020 tclPort 8020 sessionId 8020 restPort 11020 processId 49500 clientType tcl setAttribute looseNoWarning enableHangTimer False`

Could you please help explain the usage purpose for sdmPort 9020?

**Comment by therkong** [comment]
hi,   the sdmPort is for internal use only; for example, it is used by trafficModule, internal sdmStandaloneTest module, ...etc.  Users should not connect to this port.
