### ISSUE TITLE
TakeSnapshotPy method used by concurrent sessions can overwrite results

### ISSUE THREAD

**Issue by ajbalogh** [OpenIxia/IxNetwork#130]
## Issue
The TakeSnapshotPy utility method does not reflect that snapshots with the same name will overwrite each other as the snapshot directory is shared between sessions.  

## Expected Behavior
The following is the method that should contain additional comments to reflect that the snapshot directory is shared https://github.com/OpenIxia/IxNetwork/blob/178c4d35f0f2c1d28dd4d778622f1303d5085bd3/Utilities/Python/IxN_Api.py#L1209

**Comment by hubogee** [comment]
Noted!
