### ISSUE TITLE
Incorrect snapshot file at debugging session

### ISSUE THREAD

**Issue by ErikCoen** [OpenIxia/IxNetwork#137]
If you like to debug the sample code like DemoScripts\loadConfigFile.py, you should not set a breakpoint between 2 lines:
trafficItemStatistics = session.StatViewAssistant(...)
...
last row read like:
rxFrames = trafficItemStatistics.Rows[0]['Rx Frames']

It will cause a wrong time stamp so at readout of a snapshot csv file, this file does not exist.

I think the variable 'snapshot_name' is not updated with correct timestamp. Have a look at this picture.

![image](https://user-images.githubusercontent.com/9577981/190104173-9f8a76c2-ad70-4056-830d-f26aec9cb72f.png)

**Comment by ErikCoen** [comment]
Suppose you have slow machine (windows / linux), the processing time is not fast. It can cause a file IO error due to wrong time stamp.

**Comment by hubogee** [comment]
Noted!  Thanks!
