### ISSUE TITLE
Create a QuickTest without configuration file (ixncfg or json)

### ISSUE THREAD

**Issue by anandvishes** [OpenIxia/IxNetwork#142]
Hi,

I want to create and execute a QuickTest without IXIA configuration file. But couldn't find any samples. It would be helpful if anyone can share a sample for QuickTest without config file.

TIA,
Anand

**Comment by hubogee** [comment]
For support issues, please send an email to support.ix@keysight.com.  Someone from the support team will be with you shortly.  Thanks.
