### ISSUE TITLE
Using IxNetwork RestPy

### ISSUE THREAD

**Issue by roboticvedant** [OpenIxia/IxNetwork#145]
I am trying to use IxNetwork RestPy to automate my quick_tests like RFC2544 throughput,etc. The sample script provided doesn't seem to work, I was wondering if there is any other sample script that I could use which creates the topology and maps ports to physical port,

**Comment by hubogee** [comment]
Most of the restpy sample scripts create topologies and configure ports.  Try using: https://github.com/OpenIxia/IxNetwork/blob/master/RestPy/SampleScripts/bgpNgpf.py

If you need more support, please send an email to support.ix@keysight.com.  Someone from the support team will be with you shortly.  Thanks.
