### ISSUE TITLE
How to upload a chassis chain lowlevelapi tcl scripts to Sample scripts?

### ISSUE THREAD

**Issue by code164** [OpenIxia/IxNetwork#147]
I write a tcl scripts about chassis chain usage , and it can run success on Aresone with ixnetwork 9.20.
So i want to share with others. Maybe someone need it. 
[L3_Pair_9000_fcoe_pfc3_chassis_chain.zip](https://github.com/user-attachments/files/16705711/L3_Pair_9000_fcoe_pfc3_chassis_chain.zip)

**Comment by hubogee** [comment]
For support issues, please send an email to support.ix@keysight.com.  Someone will be with you shortly.  Thanks.
