### ISSUE TITLE
the script  "loadJsonConfigFile.robot" can not work 

### ISSUE THREAD

**Issue by sonicwallsun** [OpenIxia/IxNetwork#18]
the script  "loadJsonConfigFile.robot" can not work 。Error happen in executing function “”fileMgmtObj.Import Json Config File‘’， shown that "
20181018 14:21:31.029 :  INFO : 14:21:31.020000: Reading saved config file
20181018 14:21:31.032 :  FAIL : TypeError: initial_value must be unicode or None, not str
Ending test:   Robot.loadJsonConfigFile.Load a JSON config file
"

**Comment by hubertgee** [comment]
Hi sonicwallsun,

I know about this bug and this has been fixed recently.  Please get latest updates.  I verified it on Robot Framework also.

Thanks,
Hubert

**Comment by sonicwallsun** [comment]
Hi ,Huberts
I updated the script and checked again ,and the bug reproducted
And the the Modules files is not newest in git,Can you check it for me ?
Thanks
Best regards

[cid:image001.png@01D467BF.47CAE240]

**Comment by hubertgee** [comment]
Can you email me the file ixNetRestApi.py?
Which ixnetwork version are you using?

Hubert
On mobile
________________________________

**Comment by sonicwallsun** [comment]
Hi .Hubert
the version for IxNetwork is 8.40,as below:
[cid:image001.png@01D46A26.B9D802F0]
Thanks

**Comment by hubertgee** [comment]
Hi,

It should work.  Did you get the latest updates and retry?

Hubert Gee

**Comment by sonicwallsun** [comment]
row 389 and 390 in IxNetRestApiFileMgmt.py  :           import io
        configContents = io.StringIO(configContents)               . now  my python version is  2.7.14,and can not execute those two rows ,can it modified as  :   configContents = io.BytesIO(configContents)  ?
thanks

**Comment by hubertgee** [comment]
Now that you mentioned you’re using Python v2, the problem is that Python v2 uses a different module called StringIO.  I added code to support both Python versions.  I tested both versions and it’s working.  Please get the updated file IxNetRestApiFileMgmt.py and retry.


        # for python3
        if platform.python_version().startswith('3'):
            import io
            configContents = io.StringIO(configContents)

        # for python2
        if platform.python_version().startswith('2'):
            import StringIO
            configContents = StringIO.StringIO(configContents)

Thanks,
Hubert Gee

**Comment by sonicwallsun** [comment]
Now  the function “fileMgmtObj.Import Json Config File” is OK,but something wrong with the function “fileMgmtObj.Json Assign Ports”,
The IxNetwork config file and log for error are below ,can you check it for me  ,thanks !

**Comment by hubertgee** [comment]
Hi,

Don’t use jsonAssignPorts.  I’m going to remove it today.  Follow the sample scripts in Github.


    portObj = PortMgmt(mainObj)

    portObj.connectIxChassis(ixChassisIp)

    if portObj.arePortsAvailable(portList, raiseException=False) != 0:
        if forceTakePortOwnership == True:
            portObj.releasePorts(portList)
            portObj.clearPortOwnership(portList)
        else:
            raise IxNetRestApiException('\nPorts are owned by another user and forceTakePortOwnership is set to False. Exiting test.')

    portObj.releasePorts(portList)
    mainObj.configLicenseServerDetails([licenseServerIp], licenseModel)

    fileMgmtObj = FileMgmt(mainObj)
    fileMgmtObj.importJsonConfigFile(jsonConfigFile, option='newConfig')

    # Set configPortName=False because loading a saved config file assumes ports already have configured names. Don't overwrite them.
    portObj.assignPorts(portList, forceTakePortOwnership, configPortName=False)

Hubert Gee

**Comment by hubertgee** [comment]
Just a FYI.  I don’t recommend loading a json config file.  If you want to load a saved config file, load the .ixncfg binary config file instead because it’s much faster to load.  Especially if you have a large configuration, json takes a long time to load.

Using json is good for modifying an existing configuration using XPATH and great for configuration something in large quantity.  Not fast at loading a complete new configuration.

Hubert Gee

From: GEE,HUBERT (K-USA,ex1)
Sent: Friday, October 26, 2018 9:26 AM
To: 'OpenIxia/IxNetwork' <reply@reply.github.com>
Subject: RE: [OpenIxia/IxNetwork] the script "loadJsonConfigFile.robot" can not work (#18)

Hi,

Don’t use jsonAssignPorts.  I’m going to remove it today.  Follow the sample scripts in Github.


    portObj = PortMgmt(mainObj)

    portObj.connectIxChassis(ixChassisIp)

    if portObj.arePortsAvailable(portList, raiseException=False) != 0:
        if forceTakePortOwnership == True:
            portObj.releasePorts(portList)
            portObj.clearPortOwnership(portList)
        else:
            raise IxNetRestApiException('\nPorts are owned by another user and forceTakePortOwnership is set to False. Exiting test.')

    portObj.releasePorts(portList)
    mainObj.configLicenseServerDetails([licenseServerIp], licenseModel)

    fileMgmtObj = FileMgmt(mainObj)
    fileMgmtObj.importJsonConfigFile(jsonConfigFile, option='newConfig')

    # Set configPortName=False because loading a saved config file assumes ports already have configured names. Don't overwrite them.
    portObj.assignPorts(portList, forceTakePortOwnership, configPortName=False)

Hubert Gee

**Comment by sonicwallsun** [comment]
hi .Hubert Gee
thanks for you kindly and professional help.
There was still a prolblem : by using the function "def getStatsPage" ,can not get Statistics.
  and the IxNetwork version when testing is 8.40,can the function "def getStatsPage" work normal in 8.40 version?
  ###  Description :Starting 8.50, the new API to use is: /statistics/statView/<id>/data, which is in getStatsData()####
