### ISSUE TITLE
RestPy: Cannot choose correct connection scheme (https)

### ISSUE THREAD

**Issue by iwanb** [OpenIxia/IxNetwork#20]
I connect to an application server running on windows (with ConnectionManager), for some reason the code assumes that linux -> HTTPS and windows -> HTTP, but AFAIK on windows it also uses HTTPS.
The TestPlaform and Connection classes should take the scheme as argument instead of inferring it from the platform.

I'm not sure why the platform is even one of the arguments, it seems it's only used to choose the connection scheme. So I will put "linux" now even though it's running windows.

**Comment by hubertgee** [comment]
Hi iwanb,

This is fixed.  Please get updates via pip install or from Github.

Thanks,
Hubert

**Comment by iwanb** [comment]
Thank you!

Iwan
