### ISSUE TITLE
RestPy: use requests Session for efficiency

### ISSUE THREAD

**Issue by iwanb** [OpenIxia/IxNetwork#21]
In ixnetwork_restpy/connection.py the Connection object could use a Session from the requests library to reuse TCP connections:
http://docs.python-requests.org/en/master/user/advanced/#session-objects

If implemented there should also be a way to close that connection (to avoid leaking sockets).

**Comment by hubertgee** [comment]
Hi iwanb,

We currently close the tcp connection on every request and we don't support concurrent request.  In our future release, we will reuse the tcp connection.

Hubert
