### ISSUE TITLE
RestPy: Do not modify global logging configuration

### ISSUE THREAD

**Issue by iwanb** [OpenIxia/IxNetwork#25]
The TestPlatform class creates logging handles and modifies the root logger.
This should be left to the users of the API instead (or at least be optional).

We (want to) use the API from our test framework which already handles logging configuration.
ATM I would need to duplicate the TestPlatform class to work around this.

Regards,
Iwan

**Comment by hubertgee** [comment]
Hi iwanb,

This is fixed.  Please get update via pip.

Thanks,
Hubert
