### ISSUE TITLE
RestPy: Code for generating class hierarchy and doc

### ISSUE THREAD

**Issue by iwanb** [OpenIxia/IxNetwork#26]
AFAIK the code/script to generate the class hierarchy in RestPy/ixnetwork_restpy/testplatform/sessions/ is not there, will it be added or that stays proprietary?

Same for the generation of the doc in RestPy/ixnetwork_restpy/docs.

Iwan

**Comment by hubertgee** [comment]
Hi iwanb,

The auto code generator is proprietary.  If you have any question, I would be glad to answer them by  emailing me at hubert.gee@keysight.com.  I like to use the Github issue mainly for problem reporting.  

Thanks,
Hubert
