### ISSUE TITLE
createEthernetNgpf() new VLAN side-effect

### ISSUE THREAD

**Issue by bluemeerkat** [OpenIxia/IxNetwork#3]
A recent change to this function switched from using specific parameters to using a kwArgs (dictionary). Unfortunately, a small unintended change in behaviour appears to have sneaked in.

Previously, specifying vlanId=None worked fine and no VLAN is created on the Ethernet.
However, now if vlanId=None is set, this None 'vlanId' entry appears in the kwArgs dictionary. The logic to decide what to do checks for the presence of  'vlanId' value in kwArgs but does NOT check for its value being none. To cut a long story short, the result is that all Ethernet interfaces created in this way have their traffic tagged with 802.1Q headers for VLAN 1 which is not what happened before, and is not what one would expect.

**Comment by hubertgee** [comment]
Fixed.  kwargs with value None is ignored.
