### ISSUE TITLE
RestPy: lookup by Href not working as expected.

### ISSUE THREAD

**Issue by muthvar1** [OpenIxia/IxNetwork#41]
Opening this issue as a continuation to issue#40
 RestPy:Any example to retreive object using href? #40

Seems like the options provided do not work as expected, or I probably need to use a different set of procs to attain the same objective.

Has anyone tried this? I can't seem to get the ixnetwork object or any other object instance using this

session = testPlatform.Sessions.find(Id='17')
2019-03-05 00:04:34 [ixnetwork_restpy.connection] [DEBUG] GET https://10.23.239.233:443/api/v1/sessions None
2019-03-05 00:04:34 [ixnetwork_restpy.connection] [DEBUG] 200 OK
ixNetwork = session.GetObjectFromHref('/api/v1/sessions/17/ixnetwork')
ixNetwork
ixNetwork = session.GetObjectFromHref(href = '/api/v1/sessions/17/ixnetwork')
ixNetwork

r = session.GetObjectFromHref(href = '/api/v1/sessions/17/ixnetwork/topology')
r

**Comment by ajbalogh** [comment]
handles are not supported - the class properties should be used ie session.Ixnetwork.

**Comment by muthvar1** [comment]
So how else can I achieve this problem statement? I will describe the problem statement below. Can you please tell me how to achieve what I am looking for.

- I have already started a session and configured a partial configuration
- I exited the session or the script
- Now I want to get back the handle to that session and also be able to retrieve the many objects I would need to continue with my configuration. This includes the ixNetwork object, topology object, possibly vport etc that were already created as part of the initial partial config.
- What I have is the href for all these objects which I can retrieve from the api browser window, or id's in case of the session.

**Comment by muthvar1** [comment]
> handles are not supported - the class properties should be used ie session.Ixnetwork.

I am not sure I understood this? If the lookup is by href, then it should accept the href as a string right? Else this function does not seem useful to me. Like I mentioned in my problem statement in Issue#40. The href handle I have is retrieved from the api browser window.

**Comment by ajbalogh** [comment]
Every object that is multi instance supports a .find() command with options for finding specific objects.  For example Sessions allows finding by Id. Vports, topologies can be found by name. IxNetwork is a single instance object so there is no need to find it - you just access the class property on sessions and you have the object.

**Comment by muthvar1** [comment]
Just an update on this thread. Figured out one mistake I was doing here. The id in testPlatform.Sessions.find(Id='17') should be integer and not string. If string is provided it gives a random object and not the actual session you request.

**Comment by ajbalogh** [comment]
Thanks for that - i will coerce the id in the sessions class.
