### ISSUE TITLE
Restpy: What is the diference between configElement and Highlevel stream?

### ISSUE THREAD

**Issue by muthvar1** [OpenIxia/IxNetwork#43]
I was trying to append a TCP header to the ipv4 stack. In the examples I see in git,  It is being added to the config Element, but this does not get added to the stacklist in highlevel streams. What is the difference here?

**Comment by ajbalogh** [comment]
ConfigElement is a collection of TrafficItem containers such as FrameSize, FrameRate etc.
HighLevelStream is a collection of those containers duplicated from the ConfigElement.
HighLevelStream is a fan out of a ConfigElement based on rate distribution, tracking etc.
When a generate is called for a TrafficItem it overwrites any changes from a ConfigElement to HighLevelStream.
