### ISSUE TITLE
RestPy: Any reason git directories for restPy SDK was removed

### ISSUE THREAD

**Issue by muthvar1** [OpenIxia/IxNetwork#44]
Seems like only pip option is there now. Can we please restore the original directories back? We were using git clone and pull rebase to update our repos.

**Comment by ajbalogh** [comment]
The ixnetwork_restpy github repo is now here https://github.com/OpenIxia/ixnetwork_restpy and will be automatically updated whenever a new build is posted to https://pypi.org/project/ixnetwork-restpy/.
