### ISSUE TITLE
RestPy:Can a list of src and dest handles be accepted for endpoint set?

### ISSUE THREAD

**Issue by muthvar1** [OpenIxia/IxNetwork#45]
I have a list of src and dest handles. Can I send a list of src and dest handles as part of the endpointset.add()

(Pdb) src_handle_list
[<ixnetwork_restpy.testplatform.sessions.ixnetwork.topology.ipv4.Ipv4 object at 0x7fafd85ba290>]
(Pdb) dest_handle_list
[<ixnetwork_restpy.testplatform.sessions.ixnetwork.topology.ipv4.Ipv4 object at 0x7fafa38ce490>, <ixnetwork_restpy.testplatform.sessions.ixnetwork.topology.ipv4.Ipv4 object at 0x7fafa38ce790>, <ixnetwork_restpy.testplatform.sessions.ixnetwork.topology.ipv4.Ipv4 object at 0x7fafa38ce110>]
(Pdb)

I want to do the following, but the command as below does not work. It only accepts one src and one dest.

trafficItem.EndpointSet.add(Sources=src_handle_list, Destinations=dest_handle_list

**Comment by whandjr** [comment]
Hi Varghese,  are you able to join a webex session to review your use case?

**Comment by muthvar1** [comment]
Yes I am. Please send me webex details.

**Comment by whandjr** [comment]
Working on setting it up.  I'll send to you in an email.

**Comment by hubertgee** [comment]
trafficItem.EndpointSet.add(Sources=[ipv4_1.href, networkGroup_2.href], Destinations=[ipv4_2.href, networkGroup_1.href])
