### ISSUE TITLE
RestPy: Is there an api to check traffic state?

### ISSUE THREAD

**Issue by muthvar1** [OpenIxia/IxNetwork#48]
I keep hitting this issue on and off and it seems to be with scaled config. Ixnetwork does not seem to be ready to accept a traffic apply or start right after another traffic operation. I tried adding a delay of about 5 seconds after each operation but that does not help always either. 
In this instance below. I did a traffic.Stop() and then a traffic.Apply() and the command errors out. It does not happen always. But at least once out of three tries. Is there a way to check state before the apply,stop or start command. This way I do not have to add guesstimated sleep commands all throughout. 
FYI: The command does go through if I try it again.

File "/local/vamuthal/IxiaSDK/ixnetwork_restpy/connection.py", line 292, in _send_recv
    raise ServerError(response)
ServerError: https://10.23.239.233:443/api/v1/sessions/14/ixnetwork/traffic/operations/apply?deprecated=true => ERROR None Error in L2/L3 Traffic Apply

2019-03-13 22:37:56 [ixnetwork_restpy.connection] [DEBUG] POST https://10.23.239.233:443/api/v1/sessions/14/ixnetwork/operations/select?deprecated=true
{"selects": [{"inlines": [], "from": "/api/v1/sessions/14/ixnetwork/", "properties": [], "children": [{"properties": ["*"], "filters": [], "child": "tra
ffic"}]}]}
2019-03-13 22:37:56 [ixnetwork_restpy.connection] [DEBUG] 202 Accepted
2019-03-13 22:37:56 [ixnetwork_restpy.connection] [DEBUG] POST https://10.23.239.233:443/api/v1/sessions/14/ixnetwork/traffic/operations/apply?deprecate
d=true {"Arg1": "/api/v1/sessions/14/ixnetwork/traffic"}
2019-03-13 22:37:56 [ixnetwork_restpy.connection] [DEBUG] 202 Accepted
Test block action failed. Error was: Traceback (most recent call last):
  File "harness.py", line 5318, in Do_Test_Block_Action_List
    RV = self.Do_Test_Block_Action( Action=Action )
  File "harness.py", line 5851, in Do_Test_Block_Action
    Action['Action_Result_Details'] = Action['Method'](Params = Test_Block['Params'])
  File "ifabric/test_blocks/Debugger/Classes_Debugger_OnDemand_AC_HW_Ixia_optimized.py", line 1233, in Main_Action
    my_ixia.start_traffic_hlt()
  File "ifabric/ifav/libs/ixia/ixia_NGPF_Restpy.py", line 690, in start_traffic_hlt
    self.ixNetwork.Traffic.Apply()
  File "/local/vamuthal/IxiaSDK/ixnetwork_restpy/testplatform/sessions/ixnetwork/traffic/traffic.py", line 675, in Apply
    return self._execute('apply', payload=payload, response_object=None)
  File "/local/vamuthal/IxiaSDK/ixnetwork_restpy/base.py", line 279, in _execute
    response = self._connection._execute(url, payload)
  File "/local/vamuthal/IxiaSDK/ixnetwork_restpy/connection.py", line 136, in _execute
    return self._send_recv('POST', url, payload)
  File "/local/vamuthal/IxiaSDK/ixnetwork_restpy/connection.py", line 292, in _send_recv
    raise ServerError(response)
ServerError: https://10.23.239.233:443/api/v1/sessions/14/ixnetwork/traffic/operations/apply?deprecated=true => ERROR None Error in L2/L3 Traffic Apply

                Main action result: Failed

                ***Test block Main failed. Error was: Traceback (most recent call last):
  File 'harness.py', line 5318, in Do_Test_Block_Action_List
    RV = self.Do_Test_Block_Action( Action=Action )
  File 'harness.py', line 5851, in Do_Test_Block_Action
    Action['Action_Result_Details'] = Action['Method'](Params = Test_Block['Params'])
  File 'ifabric/test_blocks/Debugger/Classes_Debugger_OnDemand_AC_HW_Ixia_optimized.py', line 1233, in Main_Action
    my_ixia.start_traffic_hlt()
  File 'ifabric/ifav/libs/ixia/ixia_NGPF_Restpy.py', line 690, in start_traffic_hlt
    self.ixNetwork.Traffic.Apply()
  File '/local/vamuthal/IxiaSDK/ixnetwork_restpy/testplatform/sessions/ixnetwork/traffic/traffic.py', line 675, in Apply
    return self._execute('apply', payload=payload, response_object=None)
  File '/local/vamuthal/IxiaSDK/ixnetwork_restpy/base.py', line 279, in _execute
    response = self._connection._execute(url, payload)
  File '/local/vamuthal/IxiaSDK/ixnetwork_restpy/connection.py', line 136, in _execute
    return self._send_recv('POST', url, payload)
  File '/local/vamuthal/IxiaSDK/ixnetwork_restpy/connection.py', line 292, in _send_recv
    raise ServerError(response)
ServerError: https://10.23.239.233:443/api/v1/sessions/14/ixnetwork/traffic/operations/apply?deprecated=true => ERROR None Error in L2/L3 Traffic Apply

**Comment by muthvar1** [comment]
Just to add to this. My understanding also was that most of these calls had a state check already implemented as part of the call itself. So a callback would not have been returned unless the state is "OK" right?

**Comment by hubertgee** [comment]
Here is a simple code to check for traffic state until it is stopped:

    def waitForTrafficToStop(self, interval=3):
        while True:
            if ixNetwork.Traffic.State == 'stopped':
                ixNetwork.info('\nwaitForTrafficToStop: Traffic is stopped\n')
                return

            ixNetwork.info('\nwaitForTrafficToStop: Traffic is still running ...')
            time.sleep(interval)

        time.sleep(interval)

**Comment by muthvar1** [comment]
Thanks Hubert. Can I use the same for started also?  

ixNetwork.Traffic.State == 'started':   ??

**Comment by hubertgee** [comment]
Yes:

        Traffic states are:
            startedWaitingForStats, startedWaitingForStreams, started, stopped,
            stoppedWaitingForStats, txStopWatchExpected, locked, unapplied


Hubert Gee
