### ISSUE TITLE
load QuickTest config run it and get Report

### ISSUE THREAD

**Issue by MichaelLindner1** [OpenIxia/IxNetwork#50]
Hi,
is it possible, to load a QuickTest config run it and get an Report in RestPy? 
I am not sure at the moment, if all the features are implemented in RestPy. If not, is there some documentation, what is missing?
Thanks,
Michael

**Comment by ajbalogh** [comment]
We will be generating a new version of the library with a property QuickTest that allows for starting/stopping a test and generating a report.
