### ISSUE TITLE
RestPy:Getting a session handle for windows platform

### ISSUE THREAD

**Issue by muthvar1** [OpenIxia/IxNetwork#52]
Hi Team,
I know how to get the session handle when using the linux platform. But if I wanted to do the same for a windows session that already has configuration. How do I do this?

For linux it would be as follows

>>>session = testPlatform.Sessions.find(Id=22)
>>>session.Ixnetwork

For Windows I tried the same thing, but It doesn't work it hangs
>>>
>>> test_platform = TestPlatform('172.29.205.16', rest_port=11009, platform='windows')
test_platform.Trace = 'request_response'2019-04-09 18:48:17 [ixnetwork_restpy.connection] [INFO] using python version 2.7.13 (default, Dec 17 2016, 23:03:43)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
2019-04-09 18:48:17 [ixnetwork_restpy.connection] [INFO] using ixnetwork-restpy version 1.0.27
>>>
>>>
>>> sessions = test_platform.Sessions.find(Id=1)
2019-04-09 18:48:46 [ixnetwork_restpy.connection] [DEBUG] GET http://172.29.205.16:11009/api/v1/sessions None
2019-04-09 18:48:46 [ixnetwork_restpy.connection] [DEBUG] 307 Temporary Redirect
2019-04-09 18:48:46 [ixnetwork_restpy.connection] [DEBUG] GET https://172.29.205.16:11009/api/v1/sessions None

**Comment by hubertgee** [comment]
For regular Windows api server, the session ID is always 1 because it only support one session. 

For windows connection manager, it supports up to 10 sessions like the Linux api server:
      platform='connection_manager'

      # Change 8021 to the session ID that you want to connect to.
      session = testPlatform.Sessions.find(Id=8021)

**Comment by muthvar1** [comment]
Hi Hubert,
This was reported by another engineer and as you can see in the output he provided above, he did use session id 1.. but the call seemed to hang. It is possible there is something we are missing from our side, but can you confirm (from your tests) using session id 1 works for Windows and it does give a handle to the session object?

**Comment by hubertgee** [comment]
I connect to an existing Windows session quite often by the way how you showed it and I have not experienced any hanging.  Does it hang if doing a testPlatform.Sessions.add() ?

**Comment by muthvar1** [comment]
Yeah.. looks like even an add does hang. Is something not set correctly on our Windows api server? 
JFYI, because of the proxy settings on our windows VM.. we couldn't open up the api browser either on the the windows client. Trying to fix that too. Hoping that's not the cause for this issue?

**Comment by hubertgee** [comment]
We have other customers who configures proxy server in their Windows and that caused connection problems.  As soon as the proxy server was disabled, connection works fine.  Try disabling the proxy server temporary to see if that fixes the problem and go from there.

**Comment by muthvar1** [comment]
Yeah tried that too for localhosts and now it just hangs.. so looks like there is some problem in accessing the api browser itself on the client.. Not sure what the problem is. 
All of us seem to be seeing the same issue. Should we open a support ticket to get this resolved?

**Comment by therkong** [comment]
Varghese,
Yes, please open a support case.  I can take a look.

Regards,

Theresa Kong
Senior Tech Support Engineer
Keysight Technologies

**Comment by muthvar1** [comment]
This needs a change in how we start the IxNetwork client in Windows. Theresa from support group helped us on this. Closing this issue with resolution below.

From: Theresa Kong <theresa.kong@keysight.com>
Date: Tuesday, April 9, 2019 at 3:03 PM
To: Sameer Patel <samepate@cisco.com>, "Varghese Muthalaly (vamuthal)" <vamuthal@cisco.com>, Hubert Gee <hubert.gee@keysight.com>
Subject: RE: cannot connect to session on windows IxNetwork API server
 
I started my ixNet API Server with -restInsecure mode.   In this mode, http is used instead of https.
And yes, I can connect.
 
If you started ixNet API Server without -restInsecure, it uses https.  There are few things that can go wrong in this mode.  
If you check the Windows Events log, there might be errors that may indicate the issue.
 
- Error 11001 is permission issue.  Make sure you have
read/write permission in "c:/program data/microsoft/crypto/rsa/machinekeys" folder  for the uid that started ixNet API Server
 
 
- Error 40 is the tls 1.2 issue.  
need to add a regkey below and restart the PC
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server] "Enabled"=dword:00000000
              Note:  there was SSL key but not TLS 1.2 key
Restart of the PC is required after adding the regkey
 
 
Or you can restart your ixNet API Server with -resetInsecure option.   This can be done in the Property window of the ixNet API Sever shortcut.
