### ISSUE TITLE
Loading streams

### ISSUE THREAD

**Issue by imehrdad2012** [OpenIxia/IxNetwork#54]
Hey, 

I'm a newbie here and got a bunch of questions:

(1) Is it possible to store the streams generated by the python API and then load them? 
(2) While the samples are definitely useful, is there any place that I can find the documentation on the Python API?
(3) Is there any Python sample where I can get packet forwarding latency, jitter? or more detailed performance numbers.

Thanks!

**Comment by whandjr** [comment]
Hi Mehrdad,

Welcome to the community.  Glad you are engaging.  I’ll do my best to answer your questions, but others may be able to provide more details.

See below with my responses.

Thanks,
Wes

Wesley Hand
m: 818-312-6752

**Comment by memoradi** [comment]
Thanks for your response. 

I tried running the vxlanNgpf.py example. However, I am getting the following error about the license not being available. After running the script, I cannot even reserve my ports through the IxNetwork GUI. Before running this script, everything was working perfectly through IxNetwork & IxExplorer. Do you have any idea how to fix this issue? Note that all initial steps   of connecting to the API server and creating a new config, and checking the licensing happens c

![image](https://user-images.githubusercontent.com/45773137/56531494-fff68300-6508-11e9-9ac6-c12dfec09731.png)

![image](https://user-images.githubusercontent.com/45773137/56532103-0a654c80-650a-11e9-8ee1-77860e5a7a81.png)

**Comment by therkong** [comment]
The script that you ran probably configured the license settings incorrectly.    Below are the settings in the sample vxlanNgpf.py:

# The IP address for your Ixia license server(s) in a list.
licenseServerIp = ['192.168.70.3']
# subscription, perpetual or mixed
licenseMode = 'subscription'
# tier1, tier2, tier3, tier3-10g
licenseTier = 'tier3'
 
Did you update it to your license server settings?
If your licenses are installed on the ixia chassis,  you can set licenseServerIP to ixia chassis IP and licenseMode to 'mixed'

**Comment by memoradi** [comment]
Thanks! I was able to fix this issue after changing the subscription model to "mixed". One more question. Is there any way to hard-code the API server port number? Every time that I lose and start IxNetwork, the port number changes.

**Comment by whandjr** [comment]
Yes, there is.

The answer depends on which API server you are using.  Sounds like you are using windows API server.  If you use the Linux API server it should always use TCP port 443.  If you are starting the IxNetwork API Server on windows, it should be consistently using 11009.  If you are just running IxNetwork client, I believe it uses a different TCP ports.

Thanks,
Wes

Wesley Hand
m: 818-312-6752

**Comment by imehrdad2012** [comment]
I'm currently using the IxNetwork client: Go the API server section that opens a link on my browser where I can figure out the TCP port number. Is there any other approach to "starting the IxNetwork API Server on windows"? Where can I find the steps? Thanks!

**Comment by imehrdad2012** [comment]
Thanks for the comment. I was able to start IxNetwork API server on 11009 (Windows).
