### ISSUE TITLE
RestPy: How do I configure VLAN on Interface?

### ISSUE THREAD

**Issue by kamaboko123** [OpenIxia/IxNetwork#58]
Hi,

I would like to use VLAN at Interface.
However, I cannot find method with a name that enables vlan.

I tried following code and it is work fine.

```
test_platform = TestPlatform('10.0.0.249', rest_port=11009, platform='windows')     
test_platform.Trace = 'request_response'
sessions = test_platform.Sessions.find(Id=1)
ixnetwork = sessions.Ixnetwork
ixnetwork.NewConfig()

vports = ixnetwork.Vport.find()

interface1 = vports[0].Interface.add(Enabled=True)
interface1.Ipv4.add(Ip="10.140.1.10", Gateway="10.140.1.2", MaskWidth=24)

interface1.Vlan.VlanId = 401
interface1.Vlan.VlanEnable = True
interface1.refresh()
```

Is my code good implementation?
Otherwise do you have better way to enable VLAN?

**Comment by hubertgee** [comment]
Please use the bgpNgpf.py sample script as your reference.  It has all the common configurations.  The doc has samples too: https://www.openixia.com/userGuides/restPyDoc
Click on Samples

    ethernet1.EnableVlans.Single(True)
    ixNetwork.info('Configuring vlanID')
    vlanObj = ethernet1.Vlan.find()[0].VlanId.Increment(start_value=103, step_value=0)
