### ISSUE TITLE
SampleScripts Link lost

### ISSUE THREAD

**Issue by h9803660** [OpenIxia/IxNetwork#59]
Hi,

Link lost  URL in RestPy/Readme

https://github.com/OpenIxia/IxNetwork/RestApi/Python/RestPy/SampleScripts
https://github.com/OpenIxia/IxNetwork/RestApi/Python/RestPy/Modules

Would you fix it?

**Comment by hubertgee** [comment]
Here are the correct paths:

https://github.com/OpenIxia/IxNetwork/tree/master/RestPy/SampleScripts
https://github.com/OpenIxia/IxNetwork/tree/master/RestPy/Modules
