### ISSUE TITLE
Using a list for Mac addresses instead of increment

### ISSUE THREAD

**Issue by imehrdad2012** [OpenIxia/IxNetwork#60]
Hello, 

In my IXIA application, I create a raw traffic item where I need to pass a list of mac addresses rather than doing auto increment (like the following). How can I achieve this in RestPy? ( I know how to do this in IxNetwork but could not see any example in this repo.) Thanks!

    ixNetwork.info('Configuring Ethernet packet header')
    ethernetDstField = ethernetStackObj.Field.find(DisplayName='Destination MAC Address')
    ethernetDstField.ValueType = 'increment'
    ethernetDstField.StartValue = "00:00:00:40:08:02"
    ethernetDstField.StepValue = "00:00:00:00:00:00"
    ethernetDstField.CountValue = 1

**Comment by therkong** [comment]
Hi Mehrdad,

you can set the ValueType = 'valueList'.   See example:


ixNetwork.info('Configuring Ethernet packet header')

ethernetDstField = ethernetStackObj.Field.find(DisplayName='Destination MAC Address')

ethernetDstField.ValueType = 'valueList'

ethernetDstField.ValueList = ["00:00:00:40:08:02", "00:00:00:40:08:03", "00:00:00:40:08:05"]

Give it a try.

Regards,

Theresa Kong
Senior Tech Support Engineer
Keysight Technologies

**Comment by memoradi** [comment]
Thanks, Theresa. It worked!

After defining the list of mac addresses, I would like to turn on the full-mesh communication. 
Can you please provide any pointer on how I should do that? 

BTW, any documentation for RestPy is highly appreciated.

**Comment by therkong** [comment]
RestPy doc can be found where you installed the ixnetwork_restpy package.
If you installed it using pip install.  It gets installed on <python install dir>/Lib/site-packages.  The doc is in <python install dir>/Lib/site-packages/ixnetork_restpy/docs dir.
Open the index.html under the doc dir

Which field do you want to do “full-mesh”?   You’re referring to traffic, correct?  Are you doing Layer 2 or Layer 3 traffic?

Regards,

Theresa Kong
Senior Tech Support Engineer
Keysight Technologies

**Comment by memoradi** [comment]
Thanks for the pointer on the documentation.

I am creating VLAN-tagged IPV4 traffic in my test. In my configuration,  the src/dest IPs and src/dst mac addresses are stored in a list, e.g.,

Source IP = [A,B,C]
Dest IP = [C,D,E]
Src Mac = [X Y Z]
dst Mac = [W M N]

I'd like to send packets [A,C, X, W], [B, D, Y, M], and [C,E,Z,N]. I know how to this in IxNetwork (using one-to-one, full-mesh,.. options). 
Q1: can you please point me on how to enable this in IXIA RestPy?
Q2: For debugging purposes, Is there any way to store packets (e.g., in JSON format) using the IXIA RestPy API? I would like to get something similar to IxExplorer's packet view option.

**Comment by hubertgee** [comment]
Also, for convenience, the doc is in our openixia website:  https://www.openixia.com/userGuides/restPyDoc

Regards,
Hubert Gee

**Comment by therkong** [comment]
Are you creating traffic item with endpointSet or raw traffic?  Both examples are in createTrafficItemAddPacketHeader.py

endpointSet:
def createTrafficItem(**kwargs)

raw:
def createPacketHeader(trafficItemObj, packetHeaderToAdd=None, appendToStack=None)


If you’re creating traffic item with endpoinetSet, then you need to create Ethernet Stack and IP stack under topology/deviceGroup with the valueList that you desire.
If  you’re creating raw traffic item, then when you append  ethernet src/dest mac stack in the traffic item, you need to set ValueType to ‘valueList’ and set the ValueList.
Do the same for src/dest IP stack.

Regarding your Q2, I need to check.  I will get back to you on this.

Regards,

Theresa Kong
Senior Tech Support Engineer
Keysight Technologies

**Comment by therkong** [comment]
Regarding Q2- you can export the traffic item to json file, then download the file to your script machine:
ixnetwork.ResourceManager.ExportConfigFile(['/traffic/trafficItem[1]/descendant-or-self::*'], False, 'json', Files('ti1.json'))
local_filename = sessions.DownloadFile('ti1.json', 'ti1_local.json')

You can view ti1_local.json file.  The format will NOT be the same as Packet View in IxExplorer GUI.  However, it will contain every field and it's settings.  Please give it a try.  If you have any issues, you can open a support ticket by sending email to support.ix@keysight.com.   I can help you in more detail.

**Comment by memoradi** [comment]
Thanks, @therkong, and @hubertgee. I will create a ticket as I got more questions.

**Comment by memoradi** [comment]
@therkong
