### ISSUE TITLE
Packet capture in restpy

### ISSUE THREAD

**Issue by imehrdad2012** [OpenIxia/IxNetwork#62]
I'm trying to do packet capture using RestPy. However, the downloaded pcap is empty (while the traffic correctly flows from IXIA port 1 to 2 and the stats show %0 traffic loss). Just wanted to double check with you folks if the following steps are correct (I do have an ongoing ticket--#854652 but the progress is slow there).

**Before traffic item creation:**
 ixNetwork.Vport.find(Name='Ethernet - 002').Capture.SoftwareEnabled = True

**After traffic item creation:**
ixNetwork.StartCapture()
ixNetwork.Traffic.Apply()
ixNetwork.Traffic.Start()
flowStatistics = StatViewAssistant(ixNetwork, 'Flow Statistics')
ixNetwork.StopCapture()
ixNetwork.SaveCaptureFiles("D:\UserData\memoradi\Desktop", "trace.pcap")

**Comment by therkong** [comment]
ixNetwork.SaveCaptureFiles() most likely saves the capture file in the ixNet API Server machine at a fixed location.   If you save the return value and print it out, it should show you the path.
You can download the file with  sessions.DownloadFile(captureFilePath, localCaptureFilePath).
1st arg is the path of the capture file in ixNet API Server machine; 2nd is the downloaded file on your script machine.

**Comment by imehrdad2012** [comment]
Thanks, @therkong. ixNetwork.SaveCaptureFiles() takes two inputs: (1) directory address and (2) file name. What should I pass as the directory path on the API server? Is there any default value to be used.

**Comment by imehrdad2012** [comment]
@therkong  Can you point me to a working example traffic capture in RestPy?

**Comment by pwlodawi** [comment]
What are you trying to capture traffic or emulated protocols control traffic ? 
If traffic shouldn't you use 
ixNetwork.Vport.find(Name='Ethernet - 002').Capture.HardwareEnabled = True
?

**Comment by imehrdad2012** [comment]
Thanks, @pwlodawi. I did not know that for the data plane traffic capture I needed to set HardwareEnabled to True.
