### ISSUE TITLE
API server fails to assign port 

### ISSUE THREAD

**Issue by pwlodawi** [OpenIxia/IxNetwork#65]
Assigning port to Linux API server session fails with error 
"Port Statistics for assigned ports not ready after 90 seconds.\nThe following ports are down: /vport:1 "

Here is my code:
https://gist.github.com/pwlodawi/7d1c7512e1bc8e1f3f1a615214371ec8
here is log
https://gist.github.com/pwlodawi/1f087f1db23b631f17f64667883279cd

I'm using:
ixnetwork-restpy version 1.0.32
API server:
Application Version: 8.52.2.34
IxNetwork API Server Version: 8.52.2.3

Best Regards,

**Comment by hubertgee** [comment]
Your line is incorrect:  new_vport = ixn.Vport.find().add(Name='My port 3/2')

It should be:  new_vport = ixn.Vport.add(Name='My port 3/2')

Hubert

**Comment by pwlodawi** [comment]
Removing find() changes nothing. Again the same error.

Log with find() removed:
https://gist.github.com/pwlodawi/21ad49526b75b1d3be10fd7bd799ed40

**Comment by therkong** [comment]
Can you take a look at the ixNet API Browser?   Are there any error?   See below for example:



[cid:image001.png@01D5267E.2C61CF40]
Regards,

Theresa Kong
Senior Tech Support Engineer
Keysight Technologies

**Comment by pwlodawi** [comment]
What example ?

**Comment by pwlodawi** [comment]
Error was caused by version mismatch between API server (8.52) and chassis (8.50-SP1).
