### ISSUE TITLE
API to increment IP, MAC & VLAN by multiple steps

### ISSUE THREAD

**Issue by ThakkarJignesh** [OpenIxia/IxNetwork#69]
Is there any API or a way to increment IP, MAC and VLAN in multiple steps using custom increment [as per legacy Ixnetwork APP], shown in screenshots?

<img width="1249" alt="IXIA_IP_Increment" src="https://user-images.githubusercontent.com/53022737/61416449-96d4a080-a8a8-11e9-8b72-c1b142c3e534.png">
<img width="1255" alt="IXIA_VLAN_Increment" src="https://user-images.githubusercontent.com/53022737/61416450-976d3700-a8a8-11e9-9321-025162bab318.png">

**Comment by therkong** [comment]
Yes, there is example script in ixnetwork_restpy/samples dir.    If you did pip install ixnetwork_restpy, the samples dir will be under <your python dir>/Lib/site-packages/ixnetwork_restpy/samples.
Please take a look at multivalues.py.      Below is example on how to increment/decrement the IP address:
# set increment multivalue
ipv4.Address.Increment(start_value='7.7.7.7', step_value='8.8.8.8')
ipv4.info(ipv4.Address)

# set decrement multivalue
ipv4.Address.Decrement(start_value='6.6.6.6', step_value='5.5.5.5')
ipv4.info(ipv4.Address)

There are other example like setting it to Random, ValueList, ...etc

**Comment by ajbalogh** [comment]
The .Custom method of the Multivalue class has that functionality.

ipv4.Address.Custom(start_value='6.6.6.6', step_value='5.5.5.5', increments=[('3.3.3.3', 12, [('2.2.2.2', 20, [])])])
ipv4.info(ipv4.Address)
assert(ipv4.Address.Pattern.startswith('Custom:') is True)
