### ISSUE TITLE
[TCL-HighLevel] IxiaLoadConfigFile

### ISSUE THREAD

**Issue by kaushik2306** [OpenIxia/IxNetwork#77]
Hi,
I am using the below proc to load my existing configuation on Ixia but I am not able to load the configuration. Below is my tcl code.

set ixncfgFile C:\\Users\\abc\\Desktop\\IxiaLearnings_Files\\ISIS_1_OnePort.ixncfg
set ixNetworkTclServerIp localhost
set ixiaChassisIp <this is my chassi ip>

proc loadConfig { ixncfgFile ixNetworkTclServerIp ixiaChassisIp } {
   if {[file exists $ixncfgFile] == 0} {
	puts "\n\n** ixNet config file does not exists: $ixncfgFile\n\n"
	
    } else {
    puts "File is found"
    }

    puts "\nLoading config file: $ixncfgFile ..."

    
	set connectStatus [::ixiangpf::connect \
			       -config_file $ixncfgFile \
			       -ixnetwork_tcl_server $ixNetworkTclServerIp \
			       -device $ixiaChassisIp \
			       -session_resume_keys 1 \
			       -connect_timeout 120 \
			       -break_locks 1 
			  ]
    

    if {[keylget connectStatus status] != $::SUCCESS} {
	puts "Connecting to IxNetwork Tcl server failed\n\n$connectStatus\n"
	exit
    } else {
	puts "Successfully connected to IxNetwork Tcl server"
    }
    
    return $connectStatus
}

loadConfig $ixncfgFile $ixNetworkTclServerIp $ixiaChassisIp

**Comment by therkong** [comment]
What is the error message?
How big is your ixncfg file?   
Can you try removing -session_resume_keys 1?   
If the ixNet config is big,  with session_resume_keys 1, it may take a long time to load.

**Comment by therkong** [comment]
Hi,  were you able to resolve the issue by setting -ression_resume_keys to 0?  Removing it may not help because the default is 1.
