### ISSUE TITLE
doc does not come with installation

### ISSUE THREAD

**Issue by sshuguan** [OpenIxia/IxNetwork#78]
I installed ixnetwork_restpy through pip install ixnetwork_restpy.
But WebUI doc doses not come with the installation. 
The folder, my_installation_dir/site-packages/ixnetwork_restpy/doc, does not exist.

**Comment by therkong** [comment]
doc does not come with the installation.  Please check:
 https://openixia.github.io/ixnetwork_restpy/#/

**Comment by whandjr** [comment]
If you like to have a local copy, as some do, you can follow this step.  It assume git client is installed.

c:\TEMP>git clone https://github.com/OpenIxia/openixia.github.io.git
Cloning into 'openixia.github.io'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 125 (delta 1), reused 2 (delta 0), pack-reused 119
Receiving objects: 100% (125/125), 11.57 MiB | 3.88 MiB/s, done.
Resolving deltas: 100% (60/60), done.


Once the clone is complete this will load the index page in your default browser

c:\TEMP>openixia.github.io\ixnetwork_restpy\index.html


Regards,
Wes

Wesley Hand
m: 818-312-6752

**Comment by sshuguan** [comment]
Local copy got cloned and the pages work fine.

With regard to Linux API server,  I can not locate solid information about file download, VM install, and etc. Can some guidance be given ?

Thanks,
Sam Shangguan
sam.shangguan.ext@nokia.com

**Comment by hubertgee** [comment]
Go to this link shown below.  As for the linux api server VM installation, it is very straight forward.  Just import it on your hypervisor, power up the VM and a dhcp ip address will be displayed.  The below link will show you where to download the linux api server installation files and how to change the dhcp ip to static ip:

https://www.openixia.com/tutorials?subject=ixNetwork/linuxApiServer&page=overview.html

**Comment by whandjr** [comment]
The release notes also have instructions for the installation.

http://downloads.ixiacom.com/support/downloads_and_updates/public/ixnetwork/9.00/IxNetwork_9.00_Full_ReleaseNotes.html

Regards,
Wes

Wesley Hand
m: 818-312-6752

**Comment by therkong** [comment]
For file download, there’s sample script “file_transfer.py” in https://openixia.github.io/ixnetwork_restpy/#/samples

Below is the file content:
from ixnetwork_restpy.testplatform.testplatform import TestPlatform
from ixnetwork_restpy.files import Files


# connect to a test tool platform
test_platform = TestPlatform('127.0.0.1')
test_platform.Authenticate('admin', 'admin')
sessions = test_platform.Sessions.add()
ixnetwork = sessions.Ixnetwork
ixnetwork.NewConfig()

# add 4 vport objects
ixnetwork.Vport.add().add().add().add()

# save the configuration on the server
ixnetwork.SaveConfig(Files('sample.ixncfg'))

# get a list of remote files
print(sessions.GetFileList())

# download the remote saved configuration as some other local file
sessions.DownloadFile('sample.ixncfg', 'local.ixncfg')

# upload the local file
print(sessions.UploadFile('local.ixncfg'))

# load the remote local configuration
print(ixnetwork.LoadConfig(Files('local.ixncfg')))

# verify that the vport objects exist
assert(len(ixnetwork.Vport.find()) == 4)


Regards,

Theresa Kong
Senior Tech Support Engineer
Keysight Technologies
