### ISSUE TITLE
How to get fields from generated packets 

### ISSUE THREAD

**Issue by muthvar1** [OpenIxia/IxNetwork#79]
I have a use case where after setting a list of DSCP values for a specifc traffic stream, I then need to know which source dest pair has what DSCP field. If I were to do this on the IxNetwork UI client, I would use the view FlowGroup/Packets button on the Preview tab of the Advanced Traffic Wizard. 
Is there a way to get this detail through automation. I basically want to know what DSCP value would be generated for each SIP-DIP pair.

**Comment by hubertgee** [comment]
Previewing packets is only for GUI.  There is no API to preview traffic item packets.  To get a view of dscp values for SIP/DIP value pair, you have to enable tracking for "Source/Dest value pair" and "IPv4 Assured forwarding PHB".   Run traffic and look at the statistics:

![dscpStats](https://user-images.githubusercontent.com/35346527/68422304-c90a5680-0154-11ea-937e-ff86bfb5e36b.png)

**Comment by muthvar1** [comment]
HI Hubert,
Enabling the tracking will only show me what the resultant DSCP value is right? Not what was sent in the TX? in our specific use case the DUT translates the DSCP to a different value. So we need to know what the Transmitted DSCP value is and also what the Received value is. The latter can be extracted by using tracking. But this specific issue is for what has been transmitted
