### ISSUE TITLE
Cannot identify correct Device Group using getDeviceGroupByRouterId

### ISSUE THREAD

**Issue by Tristou27** [OpenIxia/IxNetwork#81]
Hello,

I can't correctly identify the targeted device group using this function. My topology is as follow : 
2 topologies, each associated to one physical port. In each topology, there is 2 device group, with basic multiplier = 1. 

The goal : I want to use method startstopDeviceGroup, providing a list of device group objects. So I need to use another method which will identify correct device group objects.

The issue : However, it seems that the method getDeviceGroupByRouterId is not working correctly because the iteration stop after the first device group in the first topology. 

Can you check this on your side, or may be I'm missing something ? 

Thanks
Regards,
Tristan

**Comment by hubertgee** [comment]
Fixed.
