### ISSUE TITLE
sample scripts are dos-format and indentation are inconsistent

### ISSUE THREAD

**Issue by sshuguan** [OpenIxia/IxNetwork#83]
After install ixnetwork_restpy on Linux (pip install -U --no-cache-dir ixnetwork_restpy)
1) those sample scripts under site-package/ixnetwork_restpy/samples/ have to be converted with "dos2unix". Otherwise they are not runnable by itself.
2) python complains about inconsistent indention at line,  
  from ixnetwork_restpy.errors import *
  File "/usr/local/lib/python3.7/site-packages/ixnetwork_restpy/errors.py", line 27
    self._message = message
                          ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by ajbalogh** [comment]
what version of the package are you using - we are not seeing this issue.

![errors indentation](https://user-images.githubusercontent.com/30300566/69375725-d7309a80-0c5d-11ea-90f8-114980f0aed9.png)

**Comment by sshuguan** [comment]
$ pip list | grep ixnetwork
ixnetwork-restpy 1.0.46
The problem occurs on Linux rather than Windows.

**Comment by ajbalogh** [comment]
still unable to reproduce.
![errors indentation](https://user-images.githubusercontent.com/30300566/69458199-b16dc900-0d23-11ea-86f2-5c4beab7d3ef.png)

**Comment by sshuguan** [comment]
Reinstall the package and the "inconsistent indention" is gone. Looks like someone fixed it already.
But sample scripts still need "dos2unix" conversion on Linux. here is how to reproduce:
1. edit file  /usr/local/lib/python3.7/site-packages/ixnetwork_restpy/samples/getting_started.py by add line "#!/usr/bin/env python3" as first line
2. chmod +x /usr/local/lib/python3.7/site-packages/ixnetwork_restpy/samples/getting_started.py
3. run it $ /usr/local/lib/python3.7/site-packages/ixnetwork_restpy/samples/getting_started.py
: No such file or directory
4 $ dos2unix /usr/local/lib/python3.7/site-packages/ixnetwork_restpy/samples/getting_started.py
5 run again $ /usr/local/lib/python3.7/site-packages/ixnetwork_restpy/samples/getting_started.py
Traceback (most recent call last):
......

**Comment by ajbalogh** [comment]
version 1.0.47 will have normalized \n endings for all files in the package.
