### ISSUE TITLE
how to turns traffic item "State" from "unapplied" to "applied"

### ISSUE THREAD

**Issue by sshuguan** [OpenIxia/IxNetwork#85]
My code is able to find all traffic items and enable them:

**_testpl = TestPlatform(server, rest_port=restport)
ixses = testpl.Sessions.find()   # only one session exists in my case
ixnet = ixses.Ixnetwork
trfitems = ixnet.Traffic.TrafficItem.find()
for t in trfitems: t.Enabled=True_**

But traffic items "State" are in "unapplied". How do I apply traffic item ? which api do I call ?
In our legacy python codes, methods commit() and execute('apply', '/traffic') are used.
I do not see corresponding methods in https://openixia.github.io/ixnetwork_restpy/#/reference
Please help.

**Comment by therkong** [comment]
There is Apply() and Start() under Traffic.   See code snip:

testplatform = TestPlatform('127.0.0.1')
sessions = testplatform.Sessions.add(ApplicationType='ixnrest', Name=None)
ixnetwork = sessions.Ixnetwork
traffic = ixnetwork.Traffic
traffic.Apply()
and
traffic.Start()

Regards,
Theresa

**Comment by sshuguan** [comment]
Got it. Thanks.
