### ISSUE TITLE
How to start-all/stop-all protocols with Restpy ? 

### ISSUE THREAD

**Issue by sshuguan** [OpenIxia/IxNetwork#86]
1. On ixia GUI (home tab), there are  Protocols->Start-All (or Stop-All) buttons.
What are corresponding Restpy APIs to achieve the same operations ?
2. How do I start/stop Dhcp and Dot1x protocols by Restpy APIs ?
(no such method or attributes under ...->globals->protocolStacks->dot1xglobals (or dhcpglobals)

**Comment by ajbalogh** [comment]
```
# start and stop all protocols
from ixnetwork_restpy.testplatform.testplatform import TestPlatform

testplatform = TestPlatform('127.0.0.1')
sessions = testplatform.Sessions.add()
ixnetwork = sessions.Ixnetwork
ixnetwork.StartAllProtocols()
ixnetwork.StopAllProtocols()
```

```
# start and stop dhcp protocols
from ixnetwork_restpy.testplatform.testplatform import TestPlatform

testplatform = TestPlatform('127.0.0.1')
sessions = testplatform.Sessions.add()
ixnetwork = sessions.Ixnetwork
dhcp = ixnetwork.Vport.find().ProtocolStack.Ethernet.find().DhcpEndpoint.find()
dhcp.Start()
dhcp.Stop()
```

```
# start and stop dot1x protocols
from ixnetwork_restpy.testplatform.testplatform import TestPlatform

testplatform = TestPlatform('127.0.0.1')
sessions = testplatform.Sessions.add()
ixnetwork = sessions.Ixnetwork
dot1x= ixnetwork.Vport.find().ProtocolStack.Ethernet.find().Dot1x.find()
dot1x.Dot1xStart()
dot1x.Dot1xStop()
```

**Comment by sshuguan** [comment]
thanks.

**Comment by sshuguan** [comment]
There are "Exception type: IndexError" when Dot1xStop() and Dot1xStop() executes:

2020-01-07 14:21:24,758 utils ERROR Exception type: IndexError
2020-01-07 14:21:24,758 utils ERROR Exception message: list index out of range
2020-01-07 14:21:24,760 utils ERROR Stack trace: /home/sshanggu/automation/library/ixrest.py, Line 223 getattr(vpp, 'Dot1x'+action.capitalize())(), Func: protocol
2020-01-07 14:21:24,760 utils ERROR Stack trace: /usr/local/lib/python3.7/site-packages/ixnetwork_restpy/testplatform/sessions/ixnetwork/vport/protocolstack/dot1x_fc69959d1d61682e346651101176cfda.py, Line 211 return self._execute('dot1xStop', payload=payload, response_object=None), Func: Dot1xStop
2020-01-07 14:21:24,760 utils ERROR Stack trace: /usr/local/lib/python3.7/site-packages/ixnetwork_restpy/base.py, Line 284 url = self._properties['href'], Func: _execute
2020-01-07 14:21:24,761 utils ERROR Stack trace: /usr/local/lib/python3.7/site-packages/ixnetwork_restpy/base.py, Line 115 return self._object_properties[self._index], Func: _properties

any clues?
thanks

**Comment by ajbalogh** [comment]
It appears that your utility library bypasses the actual Dot1xStart
function in the library.
The Dot1xStart function inserts any required hrefs as part of the payload
which may be missing.
Also are you using dot1x protocols from legacy protocolStack or from
topology?

**Comment by sshuguan** [comment]
the dot1x protocol is from protocolStack. below are part of my codes:

...... 
ixvps = ixnetwork.Vport.find()
for vp in ixvps:
    vpp = vp.ProtocolStack.Ethernet.find().Dot1x.find()
    vpp.Dot1xStop()             # it throws Exception IndexError 
    vpp.Dot1xStart()             # it throws Exception IndexError

**Comment by ajbalogh** [comment]
you should confirm that you have at least one Dot1x instance. the following
does not give me an indexerror.

from ixnetwork_restpy.testplatform.testplatform import TestPlatform


testplatform = TestPlatform('127.0.0.1')
sessions = testplatform.Sessions.add()
ixnetwork = sessions.Ixnetwork
ixnetwork.NewConfig()
ixnetwork.Vport.add().ProtocolStack.EthernetEndpoint.add().Range.add().Dot1xRange.add()
dot1x = ixnetwork.Vport.find().ProtocolStack.EthernetEndpoint.find().Dot1x.find()
assert(len(dot1x) == 1)
dot1x.Dot1xStart()

**Comment by sshuguan** [comment]
trying. thanks
