### ISSUE TITLE
Cannot add protocol template that contains '(', ')' characters in its name to traffic item.

### ISSUE THREAD

**Issue by Ethernet-Packet** [OpenIxia/IxNetwork#87]
From file `\IxNetwork\RestApi\Python\Modules\IxNetRestApiTraffic.py` the following function (keyword) `addTrafficItemPacketStack` throws `"No such protocolTemplate name found: Connectivity Fault Management (CFM)"`  even though "Connectivity Fault Management (CFM)" is a valid protocol template name.

The reason behind the issue is the following regex:

    if bool(re.match('^%s$' % protocolStackNameToAdd, eachProtocol['displayName'].strip(), re.I)):

in which the `(`, `)` characters are not escaped, thus the regex won't match.

As a workaround the protocol template name should be escaped upon passing it to the `addTrafficItemPacketStack` function. E.g. in Robot Framework:

    IxiaTraffic.Add Traffic Item Packet Stack    ${configEmelentsToModify}    Connectivity Fault Management \\(CFM\\)    1    append

**Comment by hubertgee** [comment]
Correct.  You need to add backslashes.
