### ISSUE TITLE
How to use suboptions in Dhcpv6client TlvProfile ?

### ISSUE THREAD

**Issue by pwlodawi** [OpenIxia/IxNetwork#89]
How to build TLV profile with option request option in dhcpv6client?

![image](https://user-images.githubusercontent.com/49796436/77006045-1350df00-6962-11ea-88ff-b9a102aceffa.png)

There is TlvProfile.Tlv.add() but how to add suboptions ?

**Comment by therkong** [comment]
Hi,  were you able to figure this out?    If not, I can open a support case for you and work on it.
What is your email address?  Or you can open a support ticket yourself by sending email to support.ix@keysight.com.

**Comment by therkong** [comment]
Hi,  I opened following support case for you.  I'll be looking into this:

Case #894622: RestPy Automation  - How to build TLV profile with option request option in dhcpv6client?

**Comment by therkong** [comment]
Here's example code:
First, you need to get default tlv template.  For the example, I got ‘Option Request’ template:
# get a default tlv template
option_request = ixnetwork.Globals.Topology.Dhcpv6client \
    .TlvEditor.find() \
    .Defaults.find() \
    .Template.find() \
    .Tlv.find(Name='Option Request')
ixnetwork.info(option_request)

# get the dhcpv6client tlv profile
tlv_profile = ixnetwork.Topology.add() \
    .DeviceGroup.add() \
    .Ethernet.add() \
    .Dhcpv6client.add() \
    .TlvProfile.find()
ixnetwork.info(tlv_profile)

# copy tlv templates into the dhcpv6client tlv profile
tlv_profile.CopyTlv(option_request)

# Now enable the sub-options [01] by setting 'IsEnabled' attribute to True
field = tlv_profile.Tlv.find(Name='\[06\] Option Request').Value.Object.find(Name='\[01\] Client Identifier').Field.find()[0]
field.IsEnabled=True
