### ISSUE TITLE
Error while starting the Scenario/DeviceGroup

### ISSUE THREAD

**Issue by ahameden** [OpenIxia/IxNetwork#94]
I am getting the below error while starting the scenario/device group.
Windows
IxNetwork v9.0

![image](https://user-images.githubusercontent.com/17122549/80185599-736e1d00-85c1-11ea-9b9d-1cbce8c24228.png)

All the configuration is done via REST, there is no error.
To overcome this, I need to reboot the port or sometimes disable flow control at port level. Sometimes have to repeat these multiple times.

Any idea why this might be happening?

I have never seen this issue with IxNetwork v8.52.

**Comment by therkong** [comment]
Hi, this seems to be issue with ixNetwork core portCPU level issue.   It's best to open a support ticket to track. You can open a support ticket by sending email to support.ix@keysight.com.   Please include ixNetwork activation code if you have one.
