### ISSUE TITLE
Some bugs in RestApi/Python/Modules/

### ISSUE THREAD

**Issue by agawande** [OpenIxia/IxNetwork#96]
Hi,

Ran into some problems when using the modules:

- timeout=900 should be timeout=timeout [here](https://github.com/OpenIxia/IxNetwork/blob/aa9aa4ccfa23c7935615864bf219a08b5825d6ea/RestApi/Python/Modules/IxNetRestApiPortMgmt.py#L418)
- Single = should be done for assignment instead of == which leads to the port being None [here](https://github.com/OpenIxia/IxNetwork/blob/aa9aa4ccfa23c7935615864bf219a08b5825d6ea/RestApi/Python/Modules/IxNetRestApi.py#L214) and [here](https://github.com/OpenIxia/IxNetwork/blob/aa9aa4ccfa23c7935615864bf219a08b5825d6ea/RestApi/Python/Modules/IxNetRestApi.py#L216) if port is not specified.
- pprint and early return should be removed from [here](https://github.com/OpenIxia/IxNetwork/blob/aa9aa4ccfa23c7935615864bf219a08b5825d6ea/RestApi/Python/Modules/IxNetRestApi.py#L1115) so that function can return the actual dict.

Thanks
Ashlesh

**Comment by therkong** [comment]
Hi,  which file and which function are you referring to?
Can you paste the code snip here?

**Comment by agawande** [comment]
They are also linked on my first comment with exact line numbers: https://github.com/OpenIxia/IxNetwork/issues/96#issue-609226021

Here are the code functions:
- In file **RestApi/Python/Modules/IxNetRestApiPortMgmt.py** the following code uses 900 instead of timeout that is passed in argument list of function **assignPorts**:

      response = self.ixnObj.waitForComplete(response, url + '/' + response.json()['id'], silentMode=False, timeout=900, ignoreException=True)

- In file **RestApi/Python/Modules/IxNetRestApi.py**, == is used in the function **\_\_init\_\_** of class Connect:

        if self.serverOs == 'windows':
            self.logInfo('Connecting to API server: windows')
            self.httpScheme = 'http'

            if self.apiServerPort is None:
                self.apiServerPort == 11009
            else:
                self.apiServerPort == serverIpPort

- In **RestApi/Python/Modules/IxNetRestApi.py** in function **getAllOpenSessionIds**, pprint and return should be removed:

 
       from pprint import pprint
       pprint(response.json())
       return

**Comment by therkong** [comment]
Thank you for reporting these issues.
I’ve updated the code and did a git pull request.
It should get into the main branch in a day or two.

Regards,
Theresa

**Comment by agawande** [comment]
Thanks! On commit #98 I think the removal of pprint and return is missed:
https://github.com/OpenIxia/IxNetwork/blob/aa9aa4ccfa23c7935615864bf219a08b5825d6ea/RestApi/Python/Modules/IxNetRestApi.py#L1115
https://github.com/OpenIxia/IxNetwork/blob/aa9aa4ccfa23c7935615864bf219a08b5825d6ea/RestApi/Python/Modules/IxNetRestApi.py#L1116
https://github.com/OpenIxia/IxNetwork/blob/aa9aa4ccfa23c7935615864bf219a08b5825d6ea/RestApi/Python/Modules/IxNetRestApi.py#L1117

**Comment by therkong** [comment]
I just checked.   pprint and return call is removed in function getAllOpenSessionIds.

Regards,
Theresa

**Comment by agawande** [comment]
Thanks!
