### ISSUE TITLE
Random RestApi Failure

### ISSUE THREAD

**Issue by kshreep** [OpenIxia/IxNetwork#97]
Exceptions occurred at random RestApi call
_______________________________________________________________________________________________________
<pre> [ERROR]: Caught Exception <IxNetRestApiException>: API call to configPacketHeaderField failed
<pre> [DEBUG]: Traceback (most recent call last):
  File "/IxNetwork/RestApi/Python/Modules/IxNetRestApiTraffic.py", line 618, in addTrafficItemPacketStack
    response = self.ixnObj.get(self.ixnObj.sessionUrl+'/traffic/protocolTemplate?skip=0&take=end')
  File "/IxNetwork/RestApi/Python/Modules/IxNetRestApi.py", line 358, in get
    raise IxNetRestApiException(errMsg)
IxNetwork.RestApi.Python.Modules.IxNetRestApi.IxNetRestApiException: GET Exception error: {"method":"GET","pathAndQuery":"/api/v1/sessions/1901/ixnetwork/traffic/protocolTemplate?take=end&skip=0","errors":[{"code":10000,"detail":"Collection was modified; enumeration operation may not execute."},{"code":10000,"detail":"System.InvalidOperationException: Collection was modified; enumeration operation may not execute.\n  at System.Collections.Generic.Dictionary`2+KeyCollection+Enumerator[TKey,TValue].MoveNext () [0x00013] in <1703987eb0444925a652fbbd73c37506>:0 \n  at IxNetwork.Traffic2.Publishers.ProtocolTemplateHandler.GetInstances () [0x00033] in <d6dd4ca555ce4f0cb0142335b5bc81dc>:0 \n  at SDMHelpers.SimplePublisher.GetChildList (SDMCsLib.GetChildListArgs args) [0x0003a] in <3d657fd98a28481ea4ae0dad8da57771>:0 \n  at SDMCsLib.SDMPeer.SANDBOX_GetChildList (SDMCsLib.GetChildListArgs args, System.Version version) [0x00067] in <3d657fd98a28481ea4ae0dad8da57771>:0 \n  at SDMCsLib.SDMSandbox.OBJECT_GetChildList (SDMCsLib.GetChildListArgs args) [0x00000] in <3d657fd98a28481ea4ae0dad8da57771>:0 \n  at SDMCsLib.RestService.SdmSandbox.GetChildren (SDMCsLib.SDMObjId sdmObjId, SDMCsLib.SDMKey child, System.Int32 skip, System.Int32 take) [0x0002d] in <07c10d65161c4de0bb3602f246fb3966>:0 \n  at SDMCsLib.RestService.SdmSandbox.GetRestIdFromSDMObjId (SDMCsLib.SDMObjId sdmObjId) [0x00048] in <07c10d65161c4de0bb3602f246fb3966>:0 \n  at SDMCsLib.RestService.SdmObjectJsonEncoder..ctor (SDMCsLib.RestService.SdmObject sdmObject, SDMCsLib.SDMObjId sdmObjId, System.Collections.Generic.List`1[T] attributeNames, System.Boolean addChildLinks, System.Boolean addMetaLink, System.Boolean addSelfLink, System.Boolean internalOverride) [0x00018] in <8faf1fb1b99943fcaae26e5c2fc5c6fb>:0 \n  at SDMCsLib.RestService.SdmObjectJsonEncoder..ctor (SDMCsLib.RestService.SdmObject sdmObject) [0x00083] in <8faf1fb1b99943fcaae26e5c2fc5c6fb>:0 \n  at SDMCsLib.RestService.SdmObject.Read () [0x000e4] in <8faf1fb1b99943fcaae26e5c2fc5c6fb>:0 \n  at SDMCsLib.RestService.V1ObjectController.Get (System.String path) [0x0001a] in <8faf1fb1b99943fcaae26e5c2fc5c6fb>:0 "}]}

In debug log,
15:44:08.475072: 
                GET: https://10.xx.xx.xx/api/v1/sessions/1901/ixnetwork/traffic/protocolTemplate?skip=0&take=end
                STATUS CODE: 400
_______________________________________________________________________________________________

IxNetRestApiException error: {"executionTimeMs":96121.0,"id":"4","state":"ERROR","progress":100,"message":null,"url":"/api/v1/sessions/1855/ixnetwork/traffic/trafficItem/operations/startstatelesstrafficblocking/4","resultUrl":"","result":"Start traffic failed\n"}
________________________________________________________________________________________________

The same code works perfectly sometimes. All parameters to the API's are correct though.
I am creating raw packet stack of 'Destination MAC Address-Source MAC Address-VLAN-IPv4'
what would be the root cause for this kind of behavior?

**Comment by therkong** [comment]
What is the ixNetwork version you're using?   Are you using Linux API Server?   There is a similar bug opened for  ixNet 9.0 Update 1.

**Comment by kshreep** [comment]
Yes. It's Linux API Server and version: 9.00.2.182

**Comment by therkong** [comment]
This bug is fixed in ixNetwork 9.0 Update 3.  Please give it a try.

**Comment by therkong** [comment]
You have Update 2.   I do have a hotfix for it on top of Update 2.   Give me a bit of time to confirm if the bug is fixed in Update 3 or not.

Regards,
Theresa

**Comment by therkong** [comment]
I can send you the hotfix file for the 9.0 Update 2 via ftp.  Please send me your email address.

**Comment by kshreep** [comment]
Thanks @therkong , email is kshreep@gmail.com
what's the better way, should I apply hotfix or update IxNetwork? we will be using IxNetwork intensively in our testing.

**Comment by therkong** [comment]
I’m waiting for engineering team’s reply on whether or not this bug is fixed in Update 3.    If it’s fixed, then use Update 3, if not, use the hotfix.  This hotfix is verified in the field.

Regards,
Theresa

**Comment by kshreep** [comment]
Sure, sounds good. Thanks.

**Comment by therkong** [comment]
Just confirmed that the fix is in IxNetwork 9.0 Update 3.

Regards,
Theresa

**Comment by kshreep** [comment]
Thanks @therkong. updating to the latest version will take some time since it's not yet out. Hence I would like to get the hotfix for this, please share, I didn't get any email yet.

**Comment by therkong** [comment]
Update 3 is already out.   Here’s the download link:
https://support.ixiacom.com/support-overview/product-support/downloads-updates/versions/68

Please scrolled down to Update 3.


[cid:image001.jpg@01D62453.6C0AF030]

Regards,
Theresa
