### ISSUE TITLE
Example for router Id config on ospf handle

### ISSUE THREAD

**Issue by muthvar1** [OpenIxia/IxNetwork#99]
Is there an example for configuring ospf router id on an ospf handle under the ipv4 handle?
Also, I do not see any examples for ospf sample scripts in git at all

**Comment by therkong** [comment]
Hi,  apologize for the delay in responding.  Can you provide your email address (your company email), your name, and ixNetwork activation code so that I can open a support ticket and work on this?  If you're not sure how to find the ixNetwork activation code, i will give you instructions.

**Comment by therkong** [comment]
Hi,  ospf router id needs to be configured under DeviceGroup/ RouterData.   Example code snip below:

ospfv2RouterId = ixNetwork.Topology.find()[0]\
    .DeviceGroup.find()[0] \
    .RouterData.find()[0] \
    .RouterId

#configure as single value
ospfv2RouterId.Single('121.0.0.1')
# configue as valueList
ospfv2RouterId.ValueList(['11.0.0.1', '22.0.0.1', '33.0.0.1', '44.0.0.1', '55.0.0.1', '66.0.0.1', '77.0.0.1', '88.0.0.1', '99.0.0.1', '100.0.0.1'])

Let me know if there's any questions/issues.
